# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HealthierApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HealthierApp
	pod 'IGListKit', '~> 4.0'
	pod 'SnapKit', '~> 5.0.0'

  target 'HealthierAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HealthierAppUITests' do
    # Pods for testing
  end

end
